zendesk/copenhagen_theme

README.md

The Ruby install command creates `./bin/compile.rb` not `./bin/compile`.

MGM: Fixing SASS compile command documentation.

---

translations.yml

We've already had `Community post elements` setting. The `Community topics elements` has a plural form, thus introducing inconsistency - and it also sounds a bit off. The decision was to go with a singular form.
@zendesk/delta

Add consistency to OOTB settings naming

---

bin/update-translations.js
package.json
yarn.lock

This PR solves the issue of exposed obsolete translation keys in the translation files. It reads the translation definitions from the `.yml` file and then it filters the keys based on the presence of the `obsolete` property.
Low.

Check for obsolete keys during translation updates

---

manifest.json
style.css
templates/article_page.hbs
templates/community_post_list_page.hbs
templates/community_post_page.hbs
templates/community_topic_list_page.hbs
templates/community_topic_page.hbs
templates/home_page.hbs
templates/section_page.hbs

This PR adds the OOTB settings to Copenhagen theme and encloses the related code in a conditional block throughout all the templates. This PR is an alternative to #26.
JIRA: [HCD-1828](https://zendesk.atlassian.net/browse/HCD-1828), [HCD-1856](https://zendesk.atlassian.net/browse/HCD-1856)
Medium - might break the layout.

Add OOTB settings V2

---

manifest.json
styles/_forms.scss

With https://github.com/zendesk/help_center/pull/16226 merged, multiselect has now focus that needs to be styled in the theme for consistency.
This PR adds the multiselect focus styles to the copenhagen theme.
@zendesk/piratos @zendesk/delta 
- Low: multiselect styling may look weird.

Add multiselect styling

---

manifest.json
style.css
styles/_article.scss
templates/article_page.hbs

Turns out the latest releases didn't ship with the correct CSS as the partials were not compiled.
This fixes this issue and also address inconsistent spacing in the article page.
@zendesk/delta @anpa

Compile CSS and small fixes

---

manifest.json
script.js

In the /requests/{id} interface, when pasting text into the comment text area using the mouse (via context menu or menu bar), the submit button does not enable. Likewise, when cutting or deleting all text from the comment box using the mouse, the submit button does not disable.
This is due to the current listener on the field only binding on `keyup`. Since mouse actions don't fire a keyup event, the interface doesn't respond to the text being entered/removed as we might intend.
This PR adjusts the default listener to bind on `input`, which should fire whenever the value of the field changes, not just on keyboard events.
- Low

Listen to input on textarea to enable request submit button

---

style.css
styles/_category.scss
styles/_home-page.scss
templates/category_page.hbs
templates/home_page.hbs
templates/section_page.hbs

These checks no longer make sense with the advent of article view permissions (they will always return `false`).
@zendesk/delta

Remove checks for internal sections

---

manifest.json
style.css
styles/_forms.scss
templates/new_community_post_page.hbs

Following https://github.com/zendesk/help_center/pull/16923
In order to support a11y (for cognitive disability in this case) we need to replace asterisk with marking optional fields.
@zendesk/delta
cc/ @zendesk/piratos

 Mark optional form fields in the New Post form

---

manifest.json
style.css
styles/_base.scss
styles/_comments.scss
templates/article_page.hbs
templates/community_post_list_page.hbs
templates/community_post_page.hbs
templates/community_topic_list_page.hbs
templates/community_topic_page.hbs
templates/footer.hbs
templates/subscriptions_page.hbs
templates/user_profile_page.hbs

Same as https://github.com/zendesk/help_center/pull/16941, this PR changes all themeable dropdowns to use `<button>`, to improve accessibility and consistency. It also removes an unused class `.page-header-item`.
@zendesk/delta
cc/ @zendesk/piratos 
Medium. Copenhagen theme dropdowns may break or look weird.

Dropdowns with <button>

---

manifest.json
style.css
styles/_request.scss
templates/request_page.hbs

Following https://github.com/zendesk/help_center/pull/17006
Users could not leave comments on requests using keyboard. In order to provide native keyboard navigation we should replace `div` and `a` tags with `button`.
@anpa @luis-almeida @zendesk/delta 
Jira: https://zendesk.atlassian.net/browse/HCJ-1715
Low - small ui update

Replace show comment container and mark as resolved with native buttons to support a11y

---

manifest.json
style.css
styles/_home-page.scss
templates/home_page.hbs

Changes in my previous PR didn't behave exactly as expected for promoted articles. This should fix the columns.
It switches to using padding instead of margin (`33%` width doesn't behave well with margins) and wraps the content of the item in a `div`, which would actually have the border (I was considering adding a special class name for it, but we don't have it for `a` either 🤷‍♂️)
@zendesk/delta
Updated removed the `div` and made `a` to wrap the icon. Also applied the similar styling to the `a` itself, also made it a block.

Fix promoted articles styling

---

manifest.json
style.css
styles/_comments.scss

It is currently possible to cause UI overflow by sending an email request with HTML wherein an element specifies its width as much wider than the max container width in the request UI. This causes the content to interfere with surrounding elements.
This PR adds an `overflow-x` rule to that container so that the wide content will be scrollable, rather than breaking out.
**Before:**
**After:**
/cc: @zendesk/delta

Handle html email request body width overflow in UI

---

manifest.json
script.js

We want to not be dependent on jQuery anymore, therefore we must refactor to vanilla JS.
Please comment if you can see that the proposed code can be simplified further without using browser support.
* JIRA: [GG-249: Refactor script.js file in CPH theme to use pure vanilla JS](https://zendesk.atlassian.net/browse/GG-249)
cc @zendesk/guide-growth 
The script is responsible for a number of important interactions in the UI. In order to move away from jQuery, a special version of Element.prototype.closest is added to support IE11 which doesn't have that prototype yet. (.closest() used to be just a jQuery feature, but was added to most modern browsers https://caniuse.com/#feat=element-closest)
Due to these risks, following features should be manually tested on all supported browsers before a …

Refactor jQuery to vanilla JS

---

manifest.json
style.css
styles/_article.scss

cc: @zendesk/guide-growth 
Low

Fix styling breaking on recently viewed and related articles

---

manifest.json
style.css
styles/_search_results.scss

@zendesk/guide-search 
@zendesk/guide-growth 
Not sure if this is the right place to add this, but CJK languages should not display search results matches in italics, they should instead use a normal style and a coloured background.
Example from google:
Before this change:
After this change:

[GS-454] Highlight using colour rather than italics for CJK searches

---

manifest.json
templates/search_results.hbs

The `path_steps` helper already returns '#' for the URL and '...' as name when a breadcrumb piece is a set of truncated items. We don't need these elipsis to have an anchor tag that points to nowhere.
* See JIRA: [PUB-1270: Remove link from ellipsis in search results in Copenhagen theme](https://zendesk.atlassian.net/browse/PUB-1270)

[PUB-1270] Do not render anchor tag on empty breadcrumb pieces

---

manifest.json
style.css
styles/_search_results.scss

Fixes a layout issues when the result snippet contains a word that's too long.
Before:
https://cl.ly/c9e09a3fc39f
After:
https://cl.ly/2e345b324d22
@zendesk/guide-search 
@zendesk/guide-growth

ZD#4402185 Fix splitting of the results search page

---

manifest.json
script.js
style.css
styles/_category.scss
styles/_section.scss
templates/category_page.hbs
templates/section_page.hbs

~For the upcoming feature of flexible hierarchies we are exposing the sections that are direct children of a section, as well as its articles.
I'm taking the section tree html from the category page and added it to the section page.~
Update:
After talking to product and design, the template design has changed, adding the subsections at the top, therefore keeping the pagination at the bottom.
It also adds an interaction with the subsections list that displays only the first 6 subsections and displays a "See all sections..." trigger to show them all.
There are many ways to do this, and I'm a little bit rusty on semantic HTML and a11y, so please let me know if you have any concerns.
The new designs also removed the border from the article list.
Some decisions that were made:
- Using an …

Adding support for Flexible Hierarchies in section page

---

manifest.json
style.css
styles/_search_results.scss

As a continuation from #69 I've changed the way we highlight search results for all the supported non-latin languages. I've used Google as inspiration for this (huehue). 
They show a different background colour for Chinese, and show all the rest of the languages in bold.
@zendesk/guide-growth @zendesk/guide-search

[GS-458] Change snippet highlight for non-latin languages

---

manifest.json
style.css
styles/_share.scss

Google+ share button is no longer in HC as of today, this PR removes redundant styling for that button.
/cc: @zendesk/guide-growth

Remove unused styling for Google+ share button

---

manifest.json
style.css
styles/_status-label.scss

During a11y audit we figured out that some status labels had poor color contrast.
I tried unifying color with what we use in Support (`pending` status uses blue, `new` status uses yellow + red) and what closest accessible versions are available in Graden.
Also I've set `font-weight` to `600` as we do in Support and in `tag` component in Garden.
Reference: https://zendesk.atlassian.net/browse/HCJ-1946

Fix color contrast for status labels, unify color with support and garden

---

manifest.json
script.js

In some cases we want to return focus to previous active element after form submit with full page reload.
Reference: https://zendesk.atlassian.net/browse/HCJ-1488

We need to return focus to elements after form submit, see HCJ-1488 for details

---

manifest.json
script.js

As `script.js` is included in all pages, `#quick-search` is not always present on the page. The PR adds a check to guard from this.

Add check in case quick search element is not present

---

manifest.json
style.css
styles/_status-label.scss

Following up on https://github.com/zendesk/copenhagen_theme/pull/84
Default background color for status icon also has insufficient color contrast. I'm suggesting to use `#058541` instead.

Fix color contrast for default status label

---

script.js
style.css
styles/_search_results.scss
templates/search_results.hbs

Collapse multibrand search filters when there are more than 5 help centers or categories:
And expand it when user clicks the button:
This is a refined version of @ellimist's original branch.
Without toggle button our SERP looks like this in mobile web:
Note that there is no way to expand filters.
With toggle button it looks like this in mobile web:
Once user clicks it, he/she will see all help centers or categories or topics.

Collapse multibrand filters when there are more than 5 items

---

style.css
styles/_search_results.scss
templates/search_results.hbs

Change multibrand theme to be aligned with the design.
Changes:
- Align author name and updated time to the right
- Align # of votes to the right and in the same line as the title
- Change the color of breadcrumbs in search results
- Use different color for doc counts in multibrand filters
Accidently closed the previous PR. There were some good discussions there:
https://github.com/zendesk/copenhagen_theme/pull/97

Align the styles of multibrand SERP with the design

---

script.js
style.css
styles/_search_results.scss
templates/search_results.hbs

- Move parentheses inside result count elements as suggested by @augustocravosilva 
- Fix the broken layout of parentheses in rtl
- Fix the issue that `see more` button is displayed when there are more than 4 filters (should be 5)
Layout in rtl before fix:
Layout in rtl after fix:

Move parentheses inside result count and fix the layout in rtl

---

manifest.json
script.js
style.css
styles/_search_results.scss
templates/search_results.hbs

This PR is to update Copenhagen theme to support multibrand search.
Please don't merge it before the GA of multibrand search.
Main changes:
- Display search results of knowledge and community in one column instead of two.
- In sidebar show help center filters, type filters and sub filters. So users can scope by help center, type (knowledge or community) and category (or topic).
- If `multibrand_search` is not enabled or there is only one help center, hide help center filters. If community is not enabled, hide type filters.
- If there are more than 5 help centers, show the first 5 and hide the rest. Users can click the `see more` button to see the rest. Same case when there are more than 5 categories or topics.
- In the search result column, align number of votes, author name and timestamp …

Copenhagen Theme Update for Multibrand Search

---

manifest.json
script.js
style.css
styles/_header.scss
styles/_icons.scss
templates/header.hbs

This PR changes the menu button from a `<span role="button">` to a `<button>`, to improve a11y (e.g. keyboard navigation), and has the positive side effect that we can reduce the scripting logic.
This also adds an svg for the menu icon.

Improve a11y for Menu Button

---

style.css
styles/_collapsible-nav.scss
templates/contributions_page.hbs
templates/user_profile_page.hbs

Adresses `aria-selected` issues with `collapsible-nav-list` in User Profiles and Contributions navigations.
While not perfect, nor consistently supported yet, `aria-current="page"` is the best solution to communicate that a link is pointing to the current page.
This issue remains to be fixed here:
https://github.com/zendesk/copenhagen_theme/blob/c239929f6c6afd04fa619f3beaafbf31867d4afa/templates/contributions_page.hbs#L5-L11
https://github.com/zendesk/copenhagen_theme/blob/8ad266702dc97e955f3cf759615459a1762c4340/templates/request_page.hbs#L5-L9
https://github.com/zendesk/copenhagen_theme/blob/af6818124445722bd63b58a429ef820380d312c1/templates/requests_page.hbs#L5-L9
https://github.com/zendesk/copenhagen_theme/blob/af6818124445722bd63b58a429ef820380d312c1/templates/subscriptions_page.hbs#L …

[GG-120] Fix collapsable-nav-list a11y

---

manifest.json

Changes the default link color to `#1F73B7` to have an acceptable contrast ratio for backgrounds with color `#FFFFFF` and `#F7F7F7`
JIRA: https://zendesk.atlassian.net/browse/GG-121

[GG-121] Change link color to improve contrast ratio

---

manifest.json

I've created a branch for API v2 changes, and this commit bumps the api_version in the manifest.
Should the theme version be bumped to `2.0.0`?

Update manifest to v2

---

manifest.json
style.css
styles/_blocks.scss
templates/community_topic_list_page.hbs
templates/home_page.hbs

I opted for `span` rather than `p`, because I think that's more semantically correct inside anchor tags.
I also updated the blocks for communities, YOLO
https://zendesk.atlassian.net/browse/GG-115

[GG-115] Use span in blocks, instead of headings

---

manifest.json
style.css
styles/_article.scss
templates/article_page.hbs

Depends on https://github.com/zendesk/help_center/pull/19739 to be merged.
Adds the icon as SVG instead of pseudo-element, and adds a title to the link to explain what the link actually does. I'm a bit conflicted on the latter, since the link's functionality isn't very apparent to seeing users. Maybe it just shouldn't be a link 🤷‍♂

[GG-771] Fix a11y for comments link on Article page

---

.gitignore

ZAT supports a local `.zat` with auth credentials (https://developer.zendesk.com/apps/docs/developer-guide/zat#authentication), but it shouldn't be checked in

Add .zat file to gitignore

---

manifest.json
templates/requests_page.hbs

A followup to https://github.com/zendesk/copenhagen_theme/pull/105 fixing same issue in Requests page navigation.

[PUB-827] Fix a11y issue in Requests page navigation

---

manifest.json
templates/community_post_list_page.hbs
templates/community_topic_page.hbs

The ticket only mentions the Topics List page, but since Post List is the same markup, I've made the change there as-well.
Recent Activities should be aligned with this change.
JIRA: https://zendesk.atlassian.net/browse/COMM-350

[COMM-350] Change topic and post list items to be sections

---

style.css
styles/_forms.scss

For accessibility reasons we want to stop indicating that the form field is required by appending `*` via css, which is ignored by the screen readers. 
Initial idea was to inline the marker into the label, but to keep it consistent with other parts of the product and general guidelines for the forms - we should instead mark optional fields with `(optional)` and not mark the required fields.
Therefore, this PR removes the style responsible for adding the `*` and coloring it.

Remove red `*` for required fields

---

manifest.json
style.css
styles/_article.scss
styles/_vote.scss
templates/article_page.hbs
templates/community_post_page.hbs

This changes should follow the following change in Help Center: https://github.com/zendesk/help_center/pull/19781
Rather than adding
* Unicode Character 'UPWARDS BLACK ARROW' (U+2B06)
* Unicode Character 'DOWNWARDS BLACK ARROW' (U+2B07)
to the vote buttons using `::before` and a font to go with those
symbols we want to use SVG to display those arrows.  To style those
icons I'm also removing the `::before` selectors for the remaining
rules that deal with styling (hover highlight etc) for these elements.
The modification of the `font-size`, `display` and `flex-direction`
was to fix a centering/alignment issue with this new approach.
I've copied over / inlined this file:
https://github.com/zendeskgarden/svg-icons/blob/master/src/16/chevron-down-fill.svg
From zendeskgarden.  For the upwards …

[COMM-90] & [COMM-628] Remove arrows from vote buttons

---

manifest.json
templates/article_page.hbs

[COMM-628]
===
Risk
===
None - Trivial HTML change
[COMM-628]: https://zendesk.atlassian.net/browse/COMM-628

[COMM-628] Do not use tick and cross for article votes

---

manifest.json
style.css
styles/_community.scss
templates/community_post_list_page.hbs
templates/community_topic_list_page.hbs

I think the heading within a popup button is strange, and that part should probably change, but this is the quickest solution without redesigning the interactions so much, while still addressing the issue.
Don't merge before the strings are translated (same as #117)
JIRA: https://zendesk.atlassian.net/browse/COMM-352

[COMM-352] Fix the heading structure on Community list page

---

.github/workflows/lighthouserc.json

[https://github.com/zendesk/copenhagen_theme/pull/127] fixs some accessibility issues in a way that `tabindex` rule starts failing. To address this the rule is excluded from accessibility score assessment. 
Low

Exclude tabindex checks from accessibility score

---

manifest.json
style.css
styles/_vote.scss
templates/article_page.hbs
templates/community_post_page.hbs

Use a CSS declaration rather than `svg[transform]` for rotating the
up-vote.  Fixes an issue where the transformation was not applied in
non-compliant browsers (e.g. IE and Safari).
None - simple style change
[COMM-721]: https://zendesk.atlassian.net/browse/COMM-721

[COMM-721] Fix flipped vote buttons

---

manifest.json
style.css
styles/_base.scss

Since `border` won't really affect checkboxes, we'll keep focus outlines
around for these.

[GG-1001] Don't disable focus outline for checkboxes

---

manifest.json
templates/community_post_list_page.hbs
templates/community_post_page.hbs
templates/community_topic_list_page.hbs
templates/community_topic_page.hbs

These button relied on `[role="button"]` styling before, which are no
longer in v2.

Add `button` class name to `button-large` elements

---

manifest.json
templates/contributions_page.hbs
templates/requests_page.hbs
templates/subscriptions_page.hbs

We already fixed this for the responsive menu, but overlooked it for desktop.

[GG-1009] Use proper ARIA attribute for top links

---

manifest.json
templates/header.hbs

`{{link 'sign_in'}}` will output a long string for unauthenticated users, and that's not what we want.

Use `sign_in` string for header link

---

manifest.json
templates/new_request_page.hbs
templates/request_page.hbs

When not available, the content won't be rendered, and that's ok.

Helpers cannot be used with an #if

---

manifest.json
style.css
styles/_actions.scss

Actions button in Firefox looks like this:

Add transparent background to actions button

---

settings/logo.svg
templates/header.hbs

Explicit size properties on `img` tag for the logo forced bigger logos to be squished. Since logos are a setting, it should be modifiable without code changes. Sizing properties are moved to the SVG, as the logo image should decide its aspect ratio.

fix(header): remove size attributes from logo img

---

.github/workflows/lighthouserc.json

- Moving aria-allowed-attr to hard assertion

Update lighthouse rules 

---

style.css
styles/_status-label.scss
templates/article_page.hbs
templates/community_post_page.hbs
templates/user_profile_page.hbs

https://zendesk.atlassian.net/browse/COMM-346
* Do not lower case the "answered" status of Community Posts
* *Do* lower case the "pending" status of Classic Requests (like we do for all other statuses of such requests); *do not* lower case the "pending" for Community Content moderation

Do not lower case 'answered' post status

---

.github/workflows/release.yml

According to https://github.com/actions/checkout/tree/master#checkout-v2:
> The auth token is persisted in the local git config. This enables your scripts to run authenticated git commands. The token is removed during post-job cleanup. Set persist-credentials: false to opt-out.
https://github.com/semantic-release/git/issues/196 also hints that the `semantic-release` step may be using the auth token set in the checkout step.
This PR sets `persist-credentials: false` in the checkout step so the `semantic-release` step can use the token from its configuration.

chore(release): set checkout step to not persist credentials

---

style.css
styles/_header.scss

Without this styling, RTL languages will overflow to the left, rather
than hiding the link.

fix: Add rtl styling for Skip Navigation link

---

style.css
styles/_base.scss
styles/_header.scss
styles/_mixins.scss
styles/_pagination.scss
styles/_recent-activity.scss
templates/header.hbs

Currently, the sign in link is not visible on mobile, since we went away from `{{user_info}}`. This re-aligns the old styling rules.

[GG-1121] fix(header): Make sign in link visible on mobile

---

templates/search_results.hbs

- Fixes bug where `type_filters` are nested in a check for community, meaning that those without communities but with external record types wouldn't see the results properly.

Update if statement to check for type filters instead of community

---

.github/PULL_REQUEST_TEMPLATE.md

IE is no longer supported for endusers: https://support.zendesk.com/hc/en-us/articles/115001505447

chore: remove IE from the PR template checklist

---

style.css
styles/_split_button.scss
styles/_user-profiles.scss
styles/index.scss
templates/user_profile_page.hbs

In order to support multiple actions on the user profile page, as new features are arriving, we need to display a split button of multiple actions rather than the current single edit profile button.

Add split button support and apply the new user profile {{actions}} helper

---

style.css
styles/_split_button.scss

The newly added split button does not match in height with other buttons used in the theme, and this shows especially on the user profile page when it is placed next to the follow/unfollow button. This PR makes sure that the button is exactly 32px tall, matching the follow/unfollow button.
Also, when hovered, the two buttons within the split button do not highlight with the darker blue, like other buttons do, so this part was added as well.
Before
After

fix(split-button): correct button height and hover-color

---

.github/workflows/theme_upload.rb

On build failure, the output will now contain a line like:
```
{"job"=>{"id"=>"43e7c3e5bc1f30c8407bcf43f4a914e8", "status"=>"failed", "errors"=>[{"message"=>"Template(s) with syntax error(s)", "code"=>"InvalidTemplates", "meta"=>{"templates/user_profile_page.hbs"=>[{"description"=>"'badges' does not exist", "line"=>253, "column"=>18, "length"=>6}]}}], "data"=>nil}}
```

More verbose errors for github workflow

---

style.css
styles/_community_badge.scss
templates/article_page.hbs
templates/community_post_page.hbs
templates/community_topic_page.hbs

Adds title badge icons (if available) to the various places where we show title badges.
Also removed title badges from the post listings - that was not designed by product design and just my bad idea that we should remove.
Can be seen live on https://z3n-kaspersor.zendesk.com/hc/en-us/profiles/377841432074
Post comment:
Article comment:
Omitted because this PR only merges into the non-main branch `badges-example`.

COMM-1183: Refined how title badges are presented

---

manifest.json
style.css
styles/_community_badge.scss
styles/_metadata.scss
styles/_user-profiles.scss
styles/index.scss
templates/article_page.hbs
templates/community_post_page.hbs
templates/user_profile_page.hbs

Heavily inspired by @zdrve's work in #203, I have done some more adjustments to make it appear more like the design abstract.
This should not be merged yet since the feature is only in EAP, and I'm also not sure if there are conventions wrt. CSS class names and attributes etc. that needs to be revised.
Post page:
User profile:
Topic page:

Community badges feature support

---

style.css
styles/_status-label.scss

This PR removes the lowercase styling for request status.

fix(request): remove lowercase styling for request status

---

templates/article_page.hbs

Fixes attachments elements appearing for assistive tech, if there are no attachments.

Don't render attachments if there are none

---

script.js

The "reply to request" page may now contain a WYSIWYG editor in stead
of a textarea. The existing mechanism for checking whether that input
field is "empty" is therefore no longer valid. Consider e.g.:
<p></p>
This string is not "empty" if interpreted as `text/plain`, however it
*is* "empty" if interpreted as `text/xml` (HTML).
We switch between the two empty-checking mechanism by looking at the
data-attribute "helper" which may have the value "wysiwyg" in which
case the new mechanism is used.
[COMM-1283]: https://zendesk.atlassian.net/browse/COMM-1283

feat(requests): [COMM-1283] Check for "emptiness" when using WYSIWYG

---

translations.yml

Added translations.yml entries for future theme setting rel. to HC brand name. With the coming visual updates of the theme (staged in PR #248), there will be an option to show the brand name next to the logo. This PR adds the string keys for that.
See COMM-1372 and ROAD-8816.

Added translations.yml entries for future theme setting

---

translations.yml

Added a translation key for a future setting which allows the user to select the link color for "visited" links.

Added translation key for visited links

---

templates/search_results.hbs

Example implementation for including Federated Search Results in the theme.
The currently available filters are:
- `help_center_filters` (pretty descriptive)
- `filters` (articles + posts)
- `subfilters` (categories + topics)
In the future, the new filters will be called:
- `source_filters` (help centers + newly defined external content sources)
- `type_filters` (articles + posts + newly defined external content types)
- `subfilters` (unchanged behaviour)
Visual Example:
At the same time, a new property `is_external` is made available on the `search_result`, that can be used to display an new tab icon:

Federated Search Example

---

style.css
styles/_article.scss
styles/_base.scss
styles/_blocks.scss
styles/_breadcrumbs.scss
styles/_buttons.scss
styles/_comments.scss
styles/_footer.scss
styles/_metadata.scss
styles/_my-activities.scss
styles/_page_header.scss
styles/_post.scss
styles/_recent-activity.scss
styles/_request.scss
styles/_search_results.scss
styles/_striped_list.scss
styles/_tables.scss
styles/_user-profiles.scss
styles/_variables.scss

We only need two font weight rules, default and semi-bold, so the others are removed.
https://zendesk.atlassian.net/browse/GG-1634

fix (styles): [GG-1634] Remove unnecessary font weights

---

manifest.json

Makes the new setting "Show brand name" default to `true`. This should be done once we have backfilled the latest version of Copenhagen, introducing the setting with it's safer-for-backwards-compatibility `false` setting.

Set the `show_brand_name` setting default to true

---

style.css
styles/_community_badge.scss
templates/article_page.hbs
templates/community_post_page.hbs
templates/user_profile_page.hbs

The PR introduces a badge widget showing either 5 badges or 4 badges and a badge placeholder showing how many more badges the user has on top of what is displayed. The badge widget is displayed in the following places:
- user profile page: user information
- article page: comment author information
- community post page: post author information
- community post page: comment author information
<details>
<summary>Screenshots</summary>
</details>
[PUB-2910]: https://zendesk.atlassian.net/browse/PUB-2910

feat: implement +n badge widget

---

templates/community_topic_page.hbs

This resolves COMM-219 which highlights that the two "New post" buttons on the topic page have different behaviours but they should both prefill the topic ID of the New post form.

fix: Adding topic ID to the bottom New post button

---

manifest.json

Removes fallback font `AppleGothic` which is causing issues for our Japanese users
Ref https://support.zendesk.com/agent/tickets/9679482

fix: Remove refs to AppleGothic

---

script.js
style.css
styles/_header.scss
templates/contributions_page.hbs
templates/header.hbs
templates/requests_page.hbs
templates/subscriptions_page.hbs

This is a combination of 2 PRs: https://github.com/zendesk/copenhagen_theme/pull/283 and https://github.com/zendesk/copenhagen_theme/pull/284
1. Merges two navigations for mobile. Currently, we have a hamburger menu and a dropdown menu that's displayed when the user clicks on the avatar.
2. Change the breakpoint for the mobile navbar. Currently, the mobile navbar is displayed only for mobile (width <= 768px). After these changes, mobile navbar will be displayed on both mobile and tablet viewports (width <= 1024px)
3. Additionally, fixes the a11y issue with desktop version of nav - all items are now displayed inside a list.
Other changes:
**User dropdown menu:**
- Use `{{ t 'profile'}}` in the `my_profile` helper in order to update the wording from "My profile" to "Profile".
- Use …

Mobile nav with new menu items

---

templates/request_page.hbs
templates/requests_page.hbs

Removes navigational markup for the Request pages that no longer link to the activity pages.

fix: Remove navigation menu on request pages

---

style.css
styles/_dropdowns.scss
templates/header.hbs

Added a missing separator between Sign out and Change password options in the user dropdown menu.
Issue: https://zendesk.atlassian.net/browse/COMM-1599
Before
After

Add separator in user dropdown

---

style.css
styles/_search.scss
templates/article_page.hbs
templates/category_page.hbs
templates/community_post_page.hbs
templates/community_topic_page.hbs
templates/new_community_post_page.hbs
templates/new_request_page.hbs
templates/search_results.hbs
templates/section_page.hbs

As part of our efforts to improve A11Y this PR introduces changes to the search icon:
* mark search icon as decorative using `aria-hidden="true"`. This improves A11Y by removing the decorative icon from the accessibility tree
* make search icon click through by adding `pointer-events: none` style
https://zendesk.atlassian.net/browse/PRODA11Y-273
Note: the changes apply to all search bars, not only the one in this screenshot

Mark search icon as decorative

---

translations.yml

This PR adds translation keys for hover link setting. This setting will be introduced in https://github.com/zendesk/copenhagen_theme/pull/297

chore: add translation keys for hover link color

---

templates/search_results.hbs

Add aria-label attributes to search result menu toggle buttons

fix: add aria labels to search result menus

---

templates/article_page.hbs
templates/community_post_page.hbs

Providing alternative text for the comments icon ("go to comments" link) as meaningful information provided visually should also be conveyed to screen reader users.

Accessible go to comments icon

---

style.css
styles/_status-label.scss
templates/request_page.hbs
templates/requests_page.hbs

Custom statuses are coming, with a limit of 45 characters, this doesn't really work well with the UI, this will help truncate statuses that would otherwise lose information due to being too large for the label. 
The reason for doing it in-theme, instead of truncating it on the backend, is that we don't want to limit our customers from the full information of a status, if they have a UI geared towards showing more characters. 
**BEFORE**
**AFTER**
_Pixel 5:_ 
_Ipad Air:_
_Desktop:_ 
_Pixel 5:_ 
_Ipad Air:_
_Desktop:_

feat: trim the statuses using css, when they're longer than the allowed space

---

translations.yml

Add strings for translations for the upcoming request list beta setting.
https://zendesk.atlassian.net/browse/GG-2335

chore: add translations for request list beta setting

---

style.css
styles/_mixins.scss

You often handle code blocks with the following markup, that conficts with our current styling:
```html
<pre>
<code class="language-javascript">console.log('Hello')</code>
</pre>
```

fix: don't apply code styles when directly nested inside a pre

---

templates/requests_page.hbs

Adds a `main-content` container to the requests page, so the "Go to main content" button works properly.
https://zendesk.atlassian.net/browse/GG-2758

fix: add main content id to the request list container

---

style.css
styles/_article.scss

The current margins conflicts with table alignment:
when applying this fix:

Fix paragraph margins inside of table cells

---

style.css
styles/_content-tags.scss
styles/index.scss
templates/article_page.hbs
templates/community_post_page.hbs
templates/new_community_post_page.hbs

This PR introduces content tags on the following three pages:
1. `New post page`: a new content tags field is added.
2. `Article page`: a new section listing the article content tags is added.
3. `Post page`: a new section listing the post content tags is added.
I couldn't use the following markup to render the content tag links:
```hbs
{{#link "search_result" content_tag_id=(id) target="_blank"}}
{{name}}
{{/link}}
```
for the following two reasons:
1. There seems to be a bug in Curlybars because `content_tag_id=(id)` does not validate. I'll need to look into that.
2. `target="_blank"` is ignored by the link helper, we would need to add the attribute to the allowlist.
New post page:
Content tags section:

feat: introduce content tags

---

style.css
styles/_search_results.scss
templates/search_results.hbs

Adds the content tag filter to the search results.

feat: add content tag filter to search results

---

style.css
styles/_search_results.scss
templates/search_results.hbs

Related to GS-2252, so that the content tag can only be deselected by clicking on the cross/close-icon.
https://user-images.githubusercontent.com/7979835/195088731-eb5c15b1-4ec8-490c-9b9f-f61d45cdccfc.mov

fix: only close content tag with click on close icon

---

templates/article_page.hbs
templates/community_post_page.hbs

This PR changes how content tag search links should be opened: on the same page, instead of in a new tab.

refactor: open content tag search links in the same tab

---

templates/search_results.hbs

This jira [ticket](https://zendesk.atlassian.net/browse/GA11YFIX-99) suggests to remove aria-expanded on section as it is not allowed on this tag. Although I could not see any difference using voiceover, as the issue with collapsed button label in mobile view which is described in the comment was fixed here https://github.com/zendesk/copenhagen_theme/pull/296. It's better to remove areia-expanded on sectoin anyway.
I'm not sure why lighthouse check is breaking for new post page but it has failed for other recent [merges](https://github.com/zendesk/copenhagen_theme/actions) as well.

Remove aria-expanded from sections in search_result page

---

style.css
styles/_article.scss
styles/_base.scss
styles/_blocks.scss
styles/_buttons.scss
styles/_collapsible-nav.scss
styles/_comments.scss
styles/_community.scss
styles/_footer.scss
styles/_forms.scss
styles/_home-page.scss
styles/_mixins.scss
styles/_post.scss
styles/_recent-activity.scss
styles/_request.scss
styles/_search.scss
styles/_search_results.scss
styles/_section.scss
styles/_striped_list.scss
styles/_tables.scss
styles/_user-profiles.scss
styles/_variables.scss

According to A11y best practices input elements should have a contrast ratio of at least 3:1 with surrounding elements.
After this change, the border color of many input elements changes from `#dddddd` to `#87929D`. The latter has a contrast ratio of > 3 with the theme's default background color: `#ffffff`.
We still have a need for some elements to use the lower contrast border color -- `#ddd` -- so this PR splits the `$border-color` SASS variable into two separate values.
| Page name    |  Page element | Fixed?           | Screenshot   |
| ------------- | ------------- | ------------- | ------------- |
| Search results page  | Search bar  | ✅                    |   <img width="1392" alt="Screenshot 2022-11-24 at 11 17 05" src="https://user-images.githubusercontent.com/1755162/203758968-99 …

[GG-2903] Improve contrast in theme elements

---

templates/article_page.hbs
templates/community_post_page.hbs
templates/user_profile_page.hbs

This PR removes the user badge filter on icons that are served with `https`. User badge icons should be served with `https` by default.

refactor(badges): remove badge icon https check

---

templates/new_community_post_page.hbs

Improves accessibility by adding id attributes and aria-describedby attributes on the fields of the new-post form.

feat: Add a11y to new-post field error messages

---

style.css
styles/_comments.scss
styles/_community_badge.scss
styles/_user-profiles.scss
templates/article_page.hbs
templates/community_post_page.hbs
templates/user_profile_page.hbs

Lighthouse reports the following a11y issue when rendering badges:
```
❌ aria-allowed-attr: `[aria-*]` attributes do not match their roles
Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes. [Learn more](https://web.dev/aria-allowed-attr/).
{
url: 'https://***.zendesk.com/hc/en-us/articles/360010829359',
selector: 'div.comment-info > div.comment-author > div.comment-meta > span.community-badge',
snippet: '<span aria-label="Badges" class="community-badge community-badge-titles">'
}
Fix all of the following:
aria-label attribute cannot be used on a span with no valid role attribute.
```
This PR:
- Updates user badges to be rendered as lists;
- Removes unused styles;
- Fixes rendering of user badges inside the comment …

fix(badges): render badges as lists

---

.github/PULL_REQUEST_TEMPLATE.md
styles/_breadcrumbs.scss
styles/_search_results.scss
templates/search_results.hbs
templates/user_profile_page.hbs

This PR updates the breadcrumbs in the search and user profile pages:
- it wraps breadcrumbs in a `nav` element with an `aria-label` attribute (translation to follow);
- it removes the `title` attribute from each crumb;
- it updates the search result markup;
- it fixes breadcrumbs RTL by using flex;
- it cleans up the search result styles;
- it updates the PR template as a follow up to https://github.com/zendesk/copenhagen_theme/pull/356;
<details>
<summary>Click here to see the before/after screenshots</summary>
</details>

fix: improve the accessibility of the breadcrumbs

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Part of the 2023 a11y OKR is that all UI-related repos must have a11y testing guidelines in their PR template.
This repo's PR template already had a bullet point related to this 🎉  but here I'm adding some more context and a link to the generalized Guide a11y testing guidelines which will also be added in other repos' templates later on.
@zendesk/vikings

Specify a11y testing needs in PR template

---

templates/article_page.hbs
templates/community_post_page.hbs

This PR removed the usage of the `role` attribute in the `vote` helper, which is actually not used in Templating API v2.

fix: remove role attribute from vote helper

---

README.md
package.json
rollup.config.mjs
yarn.lock

- Bring in `zcli`
- Make use of the new `zcli themes:preview` command
- Run `rollup` and `preview` concurrently as part of `yarn start`
We should now be able to start bypass `zat` and start the theme development environment with a single command: `yarn start` as per convention.
Next steps:
- Make use of `zcli themes:import` when available
- Deprecate all usage of `zat` in this repo, e.g. for lighthouse audits
- Remove (by then) obsolete `ruby` setup from this repo

Run `zcli themes:preview` in `yarn start`

---

templates/search_results.hbs
templates/user_profile_page.hbs

Follow up to https://github.com/zendesk/copenhagen_theme/pull/357.
This PR updates the breadcrumbs in the user profile and search results page to use translated strings in the `aria-label`.

fix: update breadcrumbs aria-label to use translated strings

---

src/navigation.js

This is reported by accessibility team to remove `aria-expanded` from section tag. This attribute applies to the button in the sidebar for mobile view and we don't need to have it for section. 
[Jira issue
](https://zendesk.atlassian.net/browse/GS-2334?atlOrigin=eyJpIjoiM2MyZTExODM1NWNmNDA1MDkzNWQ1MGVjYTU5MGNmZjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

Remove aria-expanded attribute from section tag in search result page

---

style.css
styles/_header.scss

Fixed tabbing a11y issue where a user was previously able to focus elements behind an open modal. 
https://zendesk.atlassian.net/browse/ULTRA-745
When tabbing from the URL bar we are able to focus the skip navigation link
You can see focus on the close button instead of the link behind the modal

Prevent tabbing to skip navigation link when modals are open

---

style.css
styles/_page_header.scss

One of our customers reported that when they added a new topic with a longer title,  the `New post` button was displayed under the topic, instead of inline. This behavior was confusing and unexpected.
The new style fixes this behavior.
- https://zendesk.atlassian.net/browse/ULTRA-850
The new post button is displayed on the next row instead of inline when the title of a new topic is very long
The new styling shows the header and button on the same row

Fix styling of long header

---

templates/new_request_page.hbs

The `new_request_page` template contains now a simple form (with the submit button and potentially an error text) and uses data from `request_form_data` helper.

Build request form using data helpers

---

style.css
styles/_article.scss
styles/_category.scss
styles/_recent-activity.scss
styles/_section.scss

When having a very long title without spaces, it is causing the title to overflow in different locations.

fix: ellipsis for very long titles

---

generate-import-map.mjs
rollup.config.mjs
templates/document_head.hbs

This PR improves the management of the import map, which is now generated automatically from the chunks file emitted by rollup, instead of manually doing it.
I added a plugin that runs after Rollup generates the bundle and:
1. replaces relative imports with bare imports in the emitted files
2. creates an import map and inject it in the `document_head.hbs` template, replacing the existing one.
Note: the first step is done with a basic string replace, e.g. `'./a.js'` is replaced with `'a'`, and this should cover both static imports (`import something from './a.js'`) and dynamic ones (`import('./a.js')`). Maybe there is a better way to do it, but I didn't manage to find one.

chore: added plugin for automatic importmap generation

---

package.json
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/data-types/Field.ts
src/modules/new-request-form/data-types/index.ts
src/modules/new-request-form/fields/TextInput.tsx
templates/new_request_page.hbs

This PR adds the Subject field rendered with Garden components in the New Request Form. This is a first implementation, we still need to improve the JSON serialization of some values and hide the ticket form selector when a ticket form is already selected

feat: added Garden subject field in new request form

---

.gitattributes
.gitignore

Compiled assets are regenerated upon every release. However, for side-running branches, or simply to be able to import a themes containing the latest changes, it's easier to not ignore compiled files.
This PR moves them to `.gitattributes` and set them as `generated` so they're always hidden by default in PRs.

Hide generated files instead of ignoring

---

assets/new-request-form.js
assets/shared.js
assets/vendor.js
rollup.config.mjs
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/data-types/Field.ts
src/modules/new-request-form/fields/DropDown.tsx
src/modules/new-request-form/fields/TextArea.tsx
templates/new_request_page.hbs

- Adding a basic `DropDown` component
- We might want to streamline and just use the same as for the ticket form field selector but I thought it was worth it to start with this one for ticket fields.
- Adding a basic `TextArea` component
- Rendering `anonymous_requester_email`, `description` and `textarea` type fields
Handling of state and submission in a follow up PR.

Rendering DropDown and TextArea ticket fields

---

assets/new-request-form.js
assets/vendor.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/data-types/RequestForm.tsx
src/modules/new-request-form/ticket-form-field/TicketFormField.tsx

This PR properly implements the Ticket Form Selector:
- the label is now read from `ticket_forms_instructions`
- the form selector is hidden when there is only one ticket form
- `ticket_form_field` is used to insert a hidden field to pass the selected form in the submit
- additional URL params are now preserved when a new ticket form is selected

feat: improved Ticket Form selector

---

assets/new-request-form.js
assets/shared.js
assets/vendor.js
package.json
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/TextArea.tsx
src/modules/new-request-form/fields/TextInput.tsx
src/modules/new-request-form/useSubmitHandler.tsx
yarn.lock

This PR adds the possibility to submit the New Request Form.
- Added a Submit button rendered with Garden
- Added logic to fetch the CSRF token before submitting the form.
- The logic should be more or less the same on the current implementation: the token is fetched just before submitting the form and appended as a hidden input. I didn't find a more "React-ish" version to do it, but I think it is fine
- We are temporarily using the internal endpoint
- Changed `TextInput` and `TextArea` components, using `defaultValue` instead of `value`. In this way, they are considered uncontrolled components by React. Without this change, it was impossible to change the value once a value was set by the template data
- Added an `Alert` component for displaying any eventual global error on top of the …

feat: added form submission and global form errors handling

---

script.js
src/forms.js

This PR fixes a long-standing issue with the organization dropdown on the Request page, which was impossible to use on mobile. When the user tried to interact with the dropdown, the collapsible sidebar closed itself, preventing the user to select a value.
This fix simply stops the propagation of the click event from the dropdown, to prevent the sidebar to close
Before:
https://github.com/zendesk/copenhagen_theme/assets/13420283/728f52b5-0531-40a8-a03d-3c166b4d6aca
After
https://github.com/zendesk/copenhagen_theme/assets/13420283/7426a8e5-5a0a-499c-a389-925a746d78e8

fix: fixed request page organization dropdown on mobile

---

assets/new-request-form.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/data-types/RequestForm.tsx
src/modules/new-request-form/parent-ticket-field/ParentTicketField.tsx
templates/new_request_page.hbs

Adding a hidden input field that contains the value of parent id (added only if the request is a follow-up to a previous ticket).
This change relies on both:
* https://github.com/zendesk/help_center/pull/27885
* https://github.com/zendesk/help_center/pull/27895
----

feat: add parent id hidden input field

---

assets/new-request-form.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/Input.tsx

Adding missing custom field types.
`checkbox`, `date`, `multiselect` and `tagger` to be handled in following PRs.

Rendering custom fields

---

assets/new-request-form.js
assets/vendor.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/Input.tsx

This PR fixes the input type for the `Input` component. 
The component was returning an input with the type `text` only when the field type was `text`, but we need to render a text field also for other field types (like `subject`, `regexp`, `partialcreditcard`). The type `text` is present only on custom text fields.

fix: fixed input type for text fields

---

assets/DatePicker.js
assets/new-request-form.js
assets/vendor.js
package.json
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/DatePicker.tsx
src/modules/new-request-form/fields/DropDown.tsx
templates/document_head.hbs
templates/new_request_page.hbs
yarn.lock

This PR adds the Due Date field which is shown when the ticket type is "task". It uses the Datepicker from Garden, and it is implemented as a `DatePicker` component that can be reused also for the Date custom field.
I also implemented the localization, since we just need to pass the HC locale to the date picker.
Notes:
- The `DatePicker` component is lazy-loaded since we don't always need it, but only when we need to show the due date field or when there is a Date custom field
- Right now the lazy loaded script contains only our component, while the code from the Garden Datepicker is bundled into the main `vendor.js` script. Ideally, the Garden part should be bundled into the lazy-loaded script as well. This requires a change in the Rollup config and can be addressed in a future PR.
- We …

feat: added Due Date field

---

style.css
styles/_article.scss
templates/article_page.hbs

> When a page uses heading markup that does not match the information communicated visually by the heading screen reader users may not understand the content of the page.
This PR changes the `span` tag for the "Was this article helpful?" string to an `h2` tag, as well as the styling required to make this change seamless.

[A11y] Make "Was this article helpful?" a `h2`

---

assets/CcField.js
assets/DatePicker.js
assets/new-request-form.js
assets/vendor.js
package.json
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/CcField/CcField.tsx
src/modules/new-request-form/fields/CcField/useTagsInputContainer.ts
templates/document_head.hbs
yarn.lock

This PR adds a CC field to the new request form.
We decided to implement a custom component since Garden doesn't have a component that fits our use case.
In theory, it would be possible to use a Combobox, but the UX is not optimal since it doesn't make much sense to show a popup with suggested results when the user can input any value they want, and there isn't a set of predefined values.
The implementation resembles the existing component, and it is also similar to an [example](https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/#ex2_label) shown in the ARIA Authoring Practices Guide website, where the list of recipients in rendered in a [grid](https://www.w3.org/WAI/ARIA/apg/patterns/grid/). For this reason, I used the grid container from Garden.
I tested the component …

feat: added CC Field

---

assets/DatePicker.js
assets/new-request-form.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/DatePicker.tsx

This PR adds support for the custom date field, using the DatePicker component introduced in #422.
The backend seems to accept an ISO string with a date only (like `2023-08-24`), while the Due Date field was implemented by setting an ISO string with time (like `2023-08-24T12:00:00.000Z`). 
It seems possible to pass a date only for the Due Date field as well, but the current implementation in HC sets an ISO string with time for it, and Support has the same behavior, so I decided to be consistent here. The DatePicker can be now configured to set a date-time value or a date-only value.
https://github.com/zendesk/copenhagen_theme/assets/13420283/2cdb9641-2f8c-424d-b6af-e1bf2497b91d

feat: added custom date field

---

assets/CcField.js
assets/DatePicker.js
assets/new-request-form.js
assets/shared.js
assets/vendor.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/buildNestedOptions.tsx
src/modules/new-request-form/data-types/Field.ts
src/modules/new-request-form/fields/MultiSelect.tsx
templates/new_request_page.hbs

Render a multi-select field with Garden in the CPH Theme
This component supports `flat` and `nested` options.
To handle the nested options, we use an object/hash/dictionary data structure. 
This data structure will contain: 
- an entry/key  named  **root**  that represents the `flat/non-nested` options
- an entry/key for each sub-options group named accordingly with the sub-option group name.
[ The selected values are not rendered correctly after submitting a request](https://zendesk.slack.com/archives/GSHE498CE/p1692800806162799?thread_ts=1692793685.466789&cid=GSHE498CE)
Jira: https://zendesk.atlassian.net/browse/GG-3284
https://github.com/zendesk/copenhagen_theme/assets/102560/1cd7762a-4e77-4579-b93f-2590f4af71e6

[GG-3284] Render a multiselect field with Garden in the CPH Theme

---

assets/new-request-form.js
assets/vendor.js
package.json
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/usePrefilledTicketFields.tsx
yarn.lock

This PR ports the implementation of pre-filled ticket forms into the Copenhagen theme:
- URL must not exceed 2048 characters (this an agreed value to set a limit);
- We don’t support pre-filling of credit card fields;
- Pre-filled value should be sanitized;
- We only allow a subset of tags in the description field;
- If the url has a `parent_id` param, no pre-filling happens (as the form is already pre-filled by the parent request);
- Checkbox values are `true` or `false`;
- We will need to revisit this one as currently the templating API return `on` and `off`
- When there are multiple forms, selecting one form redirects the user to the form page. We make sure that the pre-filling params are preserved when navigating.

feat: pre-filled ticket forms

---

src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/data-types/EndUserCondition.ts
src/modules/new-request-form/data-types/Field.ts
src/modules/new-request-form/data-types/RequestForm.tsx
src/modules/new-request-form/data-types/index.ts
src/modules/new-request-form/fields/Checkbox.tsx
src/modules/new-request-form/fields/DatePicker.tsx
src/modules/new-request-form/fields/DropDown.tsx
src/modules/new-request-form/fields/Input.tsx
src/modules/new-request-form/fields/TextArea.tsx
src/modules/new-request-form/fields/cc-field/CcField.tsx
src/modules/new-request-form/parent-ticket-field/ParentTicketField.tsx
src/modules/new-request-form/ticket-form-field/TicketFormField.tsx
src/modules/new-request-form/useEndUserConditions.tsx

- This means the value of checkboxes is now a `boolean` instead of `string` (`"on" | "off"`)
Still missing displaying `optional` conditional fields as we're waiting for a decision on the UI.

feat: adding support for conditional fields

---

assets/DatePicker.js
assets/new-request-form.js
assets/vendor.js
package.json
src/modules/new-request-form/fields/Checkbox.tsx
src/modules/new-request-form/fields/DatePicker.tsx
src/modules/new-request-form/fields/DropDown.tsx
src/modules/new-request-form/fields/Input.tsx
src/modules/new-request-form/fields/MultiSelect.tsx
src/modules/new-request-form/fields/TextArea.tsx
templates/new_request_page.hbs
yarn.lock

Required fields are marked:
* with `required` property on the element (done before this PR)
* visual representation of the `*`
The asterisk is explained on the top of the form, as suggested by the design and accessibility team. In the beginning we were considering having the explanation on the first of the required fields but that approach turned out to be too complicated and/or confusing considering the conditional fields, change of order, etc. 
I tested this using a Voice Over and the `required` attribute on the input informs that the field is required. Screen readers won’t read the `*` symbol.
We will need a translation for the explanation string.
I am not sure if this will behave correctly for RTL languages. I tried to test it on the existing form but I think there is more things …

feat: mark fields as required

---

assets/new-request-form.js
assets/vendor.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/CreditCard.tsx
src/modules/new-request-form/redactCreditCard.ts
src/modules/new-request-form/useSubmitHandler.tsx

This PR adds a `CreditCard` field, which redacts the credit card number on blur. The redaction happens also when the form is submitted, to ensure that the number is redacted even if the input was not blurred (for example, pressing ENTER on the Credit Card field will submit the form without blurring the input).
The redaction logic is ported from the library used in Help Center.
https://github.com/zendesk/copenhagen_theme/assets/13420283/6ac9db96-53ba-4799-a0d3-e97382d7ebfe

feat: added CreditCard field

---

assets/new-request-form.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/DropDown.tsx

The `priority` and `type` fields have a default null value, which is displayed as `-` in the input. The same value was not listed in the options menu, so when a value was selected from the dropdown, it wasn't possible to go back to the null value.
This PR fixes this issue, adding the null option to the menu, only for optional fields.
https://github.com/zendesk/copenhagen_theme/assets/13420283/7224223c-1e20-4830-acfd-7a3d1476d080

fix: added empty option for priority and type fields

---

templates/article_page.hbs

This PR adds an `aria-current="page"` attribute to the current article link in the articles' sidebar, to let screen readers announce that the link is pointing to the current page.

fix: added aria-current attribute to articles list

---

templates/community_post_list_page.hbs
templates/community_topic_page.hbs

This PR updates both the `community_post_list_page` and `community_topic_page` templates so that:
- `<ul>` and `<li>` elements are used to render the list of posts;
- A message is shown when there are no posts in the list;
- Removes an extra `div` element inside the `section` element;
Note: this PR easier to review by hiding whitespace ([link](https://github.com/zendesk/copenhagen_theme/pull/439/files?w=1));
<details>
<summary>See the screenshots bellow</summary>
</details>

Use <ul> element to render list of posts (a11y fix)

---

assets/DatePicker.js
assets/vendor.js
src/modules/new-request-form/fields/DatePicker.tsx

This PR updates the datepicker field so that it can be cleared as a regular text input.

fix: allow datepicker field to be cleared

---

assets/new-request-form.js
src/modules/new-request-form/useEndUserConditions.tsx

*context*:
When configuring end user conditions, one can "override" the field's `required` value.
We must respect the `is_required` value set int the condition's child field and copy it over into the request `field` so it can be rendered with/out the asterisk (*).

fix: use 'required' value from end user conditon

---

assets/new-request-form.js
src/modules/new-request-form/ticket-form-field/TicketFormField.tsx

There is a full page reload after the user selects a new ticket form. We want to return the focus to the dropdown for a better a11y.

Return focus to ticket form field dropdown

---

assets/new-request-form.js
src/modules/new-request-form/useEndUserConditions.tsx
src/modules/new-request-form/usePrefilledTicketFields.tsx

fix: fix 'required' state and prefilling of multiselect fields

---

assets/new-request-form.js
src/modules/new-request-form/suggested-articles/SuggestedArticles.tsx

There is now a public endpoint for ticket deflection suggestions. Let's use it.

Use the public deflection endpoint URL instead of the internal one

---

package.json
yarn.lock

Latest change in `zcli` should address a long standing issue when previewing themes on Windows machines.

Upgrading `zcli` to latest version

---

assets/useModalContainer.js
src/modules/theming/setupGardenTheme.ts

We were not setting `rtl` when setting up the garden theme.
_before_
_after_

Fixing RTL in the new request form

---

templates/request_page.hbs

The `Add/Edit/View feedback` links were meant to be opened in a new tab. This PR fixes that.

fix: open survey response links in a new tab

---

templates/request_page.hbs

Reverts zendesk/copenhagen_theme#463
Product + design decided, it was a better experience when the survey response page opened in the same window/tab.

Revert "fix: open survey response links in a new tab"

---

templates/new_request_page.hbs

Rendering missing breadcrumbs in the new request page.

Re-add breadcrumbs

---

assets/new-request-form-bundle.js
assets/vendor-bundle.js
src/modules/new-request-form/fields/Checkbox.tsx
src/modules/new-request-form/fields/CreditCard.tsx
src/modules/new-request-form/fields/DatePicker.tsx
src/modules/new-request-form/fields/DropDown.tsx
src/modules/new-request-form/fields/Input.tsx
src/modules/new-request-form/fields/MultiSelect.tsx
src/modules/new-request-form/fields/Tagger.tsx
src/modules/new-request-form/fields/TextArea.tsx

This PR enables the rendering of links for the description of ticket fields in the New Request Form. 
The auto-linking feature is provided by the backend and the text is already sanitized, so we can safely use `dangerouslySetInnerHTML`.
Before
After

feat: render links in fields description in the new request form

---

assets/new-request-form-bundle.js
src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/data-types/RequestForm.tsx
src/modules/new-request-form/fields/Input.tsx
src/modules/new-request-form/usePrefilledTicketFields.tsx

This PR fixes the value selection and the prefilling of the organization field and the prefilling of the CC field, the anonymous requester email, and the due date field.
These issues were introduced when [we moved some fields out of the ticket_fields array](https://github.com/zendesk/copenhagen_theme/pull/457). Those features stopped working since the value tracking of the controlled components and the prefilling were still working only on the ticket_fields array.
Prefill changes:
- Passing down and returning also the fields that are outside the `ticket_fields` array
- Wrapped the function in a `useMemo` since we don't need to recalculate them on each rerender
- Changed `usePrefilledTicketFields` to a normal function called  `prefillTicketFields` - it doesn't need to be a hook since we …

fix: fixed organization dropdown and ticket prefilling

---

assets/new-request-form-bundle.js
src/modules/new-request-form/useFormSubmit.tsx

This PR fixes the issue that prevented form submission when the Credit Card field contained an empty value

fix: allow empty credit card value

---

assets/new-request-form-bundle.js
src/modules/new-request-form/fields/textarea/TextArea.tsx

This PR increases the height of the `Textarea` component to 6 rows (similar height to the textarea in v3), and it adds the resize handle to it
Before:
After:

feat: increase textarea size and make it resizable

---

assets/new-request-form-bundle.js
src/modules/new-request-form/fields/CreditCard.tsx
src/modules/new-request-form/fields/cc-field/CcField.tsx
style.css
styles/_base.scss
styles/_buttons.scss
templates/article_page.hbs
templates/community_post_page.hbs
templates/new_community_post_page.hbs
templates/request_page.hbs
templates/requests_page.hbs

This PR fixes the conflict between the global styles defined in the global CSS files with the styles defined by Garden.
There were some issues caused by the global styles applied to form elements that were also applied to Garden components. 
- All forms rendered in Curlybars now have the `hbs-form` class applied
- All form element styles are scoped inside the `hbs-form` class or the `search` class for the form associated to the [search helper](https://developer.zendesk.com/api-reference/help_center/help-center-templates/helpers/#search-helper)
- Removed ad-hoc fixes in the New Request Form components

fix: Avoid Global styles / Garden styles clash

---

src/modules/new-request-form/NewRequestForm.tsx

When the Priority system field is configured with `Normal, High` field values (plus `Customer can edit` permission and `Required to submit a request` enabled), the Priority field is not shown in the Help Center ticket form. 
So, when end users try to submit tickets via Help Center, the request fails with `422` response and error `Validation failed: Priority: cannot be blank`. 
This is caused because the `Priority` ticket field `type` changes to `basic_priority` when Priority field is configured with `Normal, High`. Simply handling `basic_priority` seems to address the issue.

fix: priority field by handling basic_priority

---

templates/article_page.hbs
templates/community_post_page.hbs
templates/request_page.hbs
templates/user_profile_page.hbs

Marks small icon as decorative to prevent being read by screen readers.

fix: add aria-hidden to decorative image

---

package.json
yarn.lock

Given that we updated `dompurify` in `help_center` due to a vulnerability report, we decided to also update this library in the Copenhagen theme.
The purpose of this PR is to do update the library to version `3.0.11`, which is the latest version available that does not require an update to the minor version.

chore: update dompurify to 3.0.11

---

src/modules/new-request-form/translations/en-us.yml

We are introducingLookup fields for custom objects in the Copenhagen Theme v4 in new request form and we need to add two short strings for translation.
[Jira epic](https://zendesk.atlassian.net/jira/software/c/projects/GG/boards/1258?selectedIssue=GG-3522)
[Figma design](https://www.figma.com/design/y9oQEXp0WSp1HAAqRcrhF3/End-User-Lookup-Fields-2024-Q1?node-id=695-37365&t=BXTZ6vkX87j1qudn-0)

feat: added strings for translations for lookup field

---

CHANGELOG.md
manifest.json

This reverts commit 317dfd838a8b50bf333c3ae6e76c1e7cd03622ce.
We triggered a wrong release containing just an update for the source translation file. This PR reverts the commit to go back to the v4.0.5 version. I already deleted the relative git tag and github release

Revert "chore(release): 4.1.0"

---

bin/extract-strings.mjs

The `extract-strings` script updates the `obsolete` date for removed strings every time we run it. This PR fixes the issue by adding the `obsolete` date for removed strings only if the string is not already marked as obsolete.

chore: avoid updating obsolete date in the extract-string script

---

assets/service-catalog-bundle.js
rollup.config.mjs
src/modules/service-catalog/ServiceCatalog.tsx
src/modules/service-catalog/index.tsx
src/modules/service-catalog/renderServiceCatalog.tsx
templates/custom_pages/service_catalog.hbs
templates/document_head.hbs
templates/header.hbs

Added template and new module in custom pages for service catalog. It is now initialized only with an “Hello World“ placeholder app. Added a button on the header to open a new page, the link to it is now hardcoded and will be changed later (it needs to be added in HC). 
Jira: [Setting up a new "Hello World" app in the Copenhagen theme for Service Catalog](https://zendesk.atlassian.net/browse/GG-3853)

feat: add new template and module for service catalog

---

assets/new-request-form-bundle.js
assets/shared-bundle.js
src/modules/new-request-form/fields/cc-field/useTagsInputContainer.ts

When we updated for v4, we changed the behavior of the CC field slightly. Before, if we clicked outside the input box, we would validate the current string and turn it into a tag, when valid. Currently, we are not doing that and we are just saving the input.
Since this feature is useful for our users, we are re-adding this feature in this PR. 
JIRA: [GG-3804](https://zendesk.atlassian.net/browse/GG-3804)
Need to convert this to a gif
https://github.com/user-attachments/assets/e14acd12-db72-40be-9346-f3142cfa9587
[GG-3804]: https://zendesk.atlassian.net/browse/GG-3804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: validate CC tag when leaving the field

---

assets/service-catalog-bundle.js
assets/shared-bundle.js
src/modules/service-catalog/ServiceCatalogItemPage.tsx
src/modules/service-catalog/index.tsx
src/modules/service-catalog/renderServiceCatalogItem.tsx
src/modules/service-catalog/translations/en-us.yml
templates/custom_pages/service_catalog_item.hbs

Added view for service catalog single item. For now showing only Title and description and button for submmiting a request (without any action). Data is mocked for now as backend is still in development and we are merging into feature branch not master.
[Implement rendering the Service Catalog Item Name and description](https://zendesk.atlassian.net/browse/GG-3879)
Collapsible description:
https://github.com/user-attachments/assets/2e672b5e-0bb3-4243-a879-d2358666ab0d
With button:
For small screens:

Service catalog item page

---

src/modules/new-request-form/NewRequestForm.tsx
src/modules/new-request-form/fields/DatePicker.tsx
src/modules/new-request-form/usePrefilledTicketFields.tsx

This PR fixes the prefilling of date fields in the Request Form.
The prefill value for date fields uses the `YYYY-MM-DD` format. We create a new Date object from that value in the Datepicker component, and this [creates a date with the time at 00:00:00 UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format).
For example, for a user in the `GMT-7` timezone, `new Date('2025-10-25')` returns `Fri Oct 25 2025 00:00:00 UTC` or `Fri Oct 24 2025 17:00:00 GMT-0700`  in his timezone.
Garden by default formats the date using the user timezone, so in this case we were showing `October 24, 2024`. This PR changes the formatting using UTC as a timezone.
We were not validating the date passed in the URL. If the user passed a value like …

[GG-3938] Fixed date fields prefilling

---

assets/service-catalog-bundle.js
src/modules/service-catalog/ServiceCatalogItemPage.tsx
src/modules/service-catalog/ServiceCatalogList.tsx
src/modules/service-catalog/components/service-catalog-item/CollapsibleDescription.tsx
src/modules/service-catalog/components/service-catalog-list-item/ServiceCatalogListItem.tsx
src/modules/service-catalog/components/useItemFormFields.tsx
src/modules/service-catalog/renderServiceCatalogItem.tsx
src/modules/service-catalog/useServiceCatalogItem.tsx
templates/header.hbs
templates/service_page.hbs

Removed mock and call to Custom Objects API and instead use target endpoints created for Service Catalog:
```
/api/v2/help_center/service_catalog/items.json
/api/v2/help_center/service_catalog/items/{id}.json
```
For EAP we are reading the service item id from the URL as we are passing it by clicking the item on the list and redirecting. to the service item page. For GA we will read it from curlybars. 
Added component for description for service item to handle showing the "read more" button when the description is shorter.
[Jira issue GG-3951](https://zendesk.atlassian.net/browse/GG-3951?atlOrigin=eyJpIjoiNWE4NTUwMzljOWM5NDZiMTkzMzhkYTI3YWZkNmE2NzUiLCJwIjoiaiJ9)

Use target endpoints for Service Catalog list and item

---

assets/fetchCsrfToken-bundle.js
assets/new-request-form-bundle.js
assets/service-catalog-bundle.js
assets/shared-bundle.js
src/modules/new-request-form/fetchCsrfToken.ts
src/modules/service-catalog/ServiceCatalogItemPage.tsx
src/modules/service-catalog/components/service-catalog-item/ItemRequestForm.tsx
src/modules/service-catalog/components/useItemFormFields.tsx
src/modules/service-catalog/data-types/ServiceRequestResponse.ts
src/modules/service-catalog/submitServiceItemRequest.tsx
src/modules/service-catalog/translations/en-us.yml
src/modules/shared/notifications/addFlashNotification.ts
templates/header.hbs

Added a functionality to submit a service catalog item request. Added validation to the form. Reorganize the structure of `ServiceCatalogItemPage.tsx` so the submit button is with the corresponding form. We have fixed values for subject and description in the request and it is in English only. This is probably only for EAP.
[GG-3862](https://zendesk.atlassian.net/browse/GG-3862?atlOrigin=eyJpIjoiMmQxZjUzYWQ5NmMwNGM2OGEyYjJjOTA5NWM2ZDM2NjAiLCJwIjoiaiJ9)
Form with validation: 
Requested service view:
[GG-3796]: https://zendesk.atlassian.net/browse/GG-3796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GG-3881]: https://zendesk.atlassian.net/browse/GG-3881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

Post request for service catalog item

---

style.css
styles/_request.scss

In Japanese, having the single character broken into another line, provides another word meaning. We want to make sure the text is only broken at points that still preserve the message meaning of "Last activity"
Before
After

fix: prevent text overflow in Japanese

---

templates/header.hbs

We added Service Catalog linker in this PR: https://github.com/zendesk/help_center/pull/30861 so now we need to use this link in Copenhagen Theme.

feat: add proper link to service catalog list

---

src/modules/service-catalog/translations/en-us.yml

This PR adds the source file for the translations used in the Service Catalog pages. I am targeting the master branch because our internal tooling is fetching the translations from master. So, to start the translation process, we need to push the YAML file on master even if the code is still in the feature  branch: https://github.com/zendesk/copenhagen_theme/tree/service-catalog-eap

chore: added translation strings for the Service Catalog

---

src/modules/ticket-fields/translations/en-us.yml

This PR adds the source file for the translations used in the Ticket Fields module. We are using ticket fields in two modules now so we decided to separate fields from new request form. I am targeting the master branch because our internal tooling is fetching the translations from master. So, to start the translation process, we need to push the YAML file on master even if the code is still in the feature branch: https://github.com/zendesk/copenhagen_theme/tree/service-catalog-eap

chore: translations for ticket fields module

---

src/modules/shared/translations/en-us.yml

Added ErrorBoundary component with default error screen so we need translations for it.

chore: add new string for translations

---

README.md
bin/extract-strings.mjs
bin/update-modules-translations.mjs
package.json
yarn.lock

This PR adds some improvements to the scripts used for downloading and extracting translation strings for the JS modules. The scripts were added when we had only one module, so they needed some tweaks to make it easier to work with multiple modules.
- Removed the `MODULES` mapping. Now the script searches for all the files matching the `src/modules/**/translations/en-us.yml` glob and downloads the translation files.
- Removed the need to specify the package name, source file glob, and output file as args.  The script now searches for all the files matching the `src/modules/**/translations/en-us.yml` glob and extracts strings for each module using the `src/modules/[MODULE_NAME]/**/*.{ts,tsx}` glob.
- Added the ability to extract strings for all modules or a single module, passing a …

i18n scripts improvements

---

.github/workflows/lighthouse.yml

The `lighthouse` check started to fail recently, and it is caused by the fact that the `ubuntu-latest` image on Github Actions has been automatically upgraded to 24.04, and we need to pass an additional config to make `puppeteer` work on this version.
Ref: https://pptr.dev/troubleshooting#issues-with-apparmor-on-ubuntu
The same approach is used by Puppeteer itself in their repo: https://github.com/puppeteer/puppeteer/pull/13196

chore: fixed lighthouse check on CI

---

src/modules/shared/translations/en-us.yml

This PR adds the new `cph-theme-shared.close-label` translation string on `master`, so it can be translated

chore(i18n): added shared translation string

---

.github/workflows/checks.yml
.github/workflows/release.yml
.releaserc

I created a new [beta branch](https://github.com/zendesk/copenhagen_theme/tree/beta) from master, where we are going to merge features that are not ready to be merged on master. We will soon merge the `service-catalog-eap` on this branch. The branch has been protected on GitHub as the master, to avoid pushes without approved PRs and so on.
With this PR I am adding support for this branch on CI. We will start to run the `checks` and `release` on pushes to this branch like we do on master, and `semantic-release` has been configured to update the changelog and create a release on this branch. The releases will be created as beta releases. For example, now we are on `v4.2.7` on `master`, and when we merge something on the beta branch we should have a new `v4.3.0-beta.X` version

chore: added suport for beta branch on CI

---

src/modules/approval-requests/translations/en-us.yml

https://github.com/zendesk/copenhagen_theme/pull/575 accidentally added text to a key vs. the label. This PR addresses that while also adding a translation and updating a value.

chore: fix approval-requests translation key and add translation

---

src/modules/service-catalog/submitServiceItemRequest.tsx

This PR fixes the display of error messages on the Service item page. We were passing the `locale` parameter in the body instead of as a query parameter, so the messages were not translated
Before:
After:

fix: display translated error messages for service submission

---

src/modules/new-request-form/data-types/Field.ts
src/modules/new-request-form/getVisibleFields.test.tsx
src/modules/new-request-form/getVisibleFields.tsx

The end-user conditions for checkbox fields with unselected values were not being applied correctly.
This was due to the fact that the conditions were not being applied at the first page load, when the field value has a default value of null, because we were comparing it with the condition value of false.

fix: apply end user conditions for checkbox fields correctly

---

templates/header.hbs

This PR fixes an accessibility issue with the user dropdown menu on mobile. We were incorrectly setting a `menuitem` role to the links in the dropdown, which is not valid for WCAG since they don't have a container element with a `menu` role. The issue was reported by a customer and it is also reported by a11y checker tools.:
This PR just removes the unneeded role, the mobile menu seems already compatible with the suggested APG pattern for navigation menus: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/
The change doesn't seem to affect the styling of the menu items in any way.
Before:
After:

fix(a11y): removed menuitem role from user mobile navbar

---

src/modules/service-catalog/translations/en-us.yml

This PR brings the changes about obsolete strings added in #567 on master.

chore: mark unused strings for service-catalog as obsolete

---

assets/approval-requests-bundle.js
src/modules/approval-requests/ApprovalRequestPage.test.tsx
src/modules/approval-requests/components/approval-request-list/ApprovalRequestListFilters.test.tsx
src/modules/approval-requests/components/approval-request-list/ApprovalRequestListFilters.tsx
src/modules/approval-requests/components/approval-request/ApprovalRequestDetails.test.tsx
src/modules/approval-requests/components/approval-request/ApprovalRequestDetails.tsx
src/modules/approval-requests/components/approval-request/ApprovalRequestPreviousDecision.test.tsx
src/modules/approval-requests/components/approval-request/ApprovalRequestPreviousDecision.tsx
src/modules/approval-requests/translations/en-us.yml
src/modules/approval-requests/types.ts

This PR adds the Previous Decision display on a withdrawn Approval Request. It also updates the types to accommodate for the API changes to surface the withdrawn_reason and the decisions.

feat(TAA-360): add the Previous Decision display on a withdrawn Approval Request

---

src/modules/approval-requests/translations/en-us.yml

Updating the translation for `Status` to not include a colon and adding a translation for `Previous decision`

chore: add 2 new translations for the approval-requests module

---

src/modules/approval-requests/components/approval-request/ApprovalRequestDetails.tsx

This PR fixes the issue where the comment field would display nothing if the comment was null or undefined. Now, it will display a hyphen (-) in such cases.
JIRA: [TAA-393](https://zendesk.atlassian.net/browse/TAA-393)
Before:
After:
[TAA-393]: https://zendesk.atlassian.net/browse/TAA-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TAA-393: Updated to display hyphen incase of empty comment

---

assets/approval-requests-bundle.js
src/modules/approval-requests/ApprovalRequestPage.tsx
src/modules/approval-requests/components/approval-request-list/ApprovalRequestListFilters.tsx
src/modules/approval-requests/components/approval-request/ApprovalTicketDetails.tsx
src/modules/approval-requests/components/approval-request/ApproverActions.tsx

These changes should have been included in https://github.com/zendesk/copenhagen_theme/pull/592 but were mistakenly not committed.
This updates the styles and the label for the filters dropdown so that it shows the translated text.
Before:
After:

chore(TAA-407): adjust RTL styles

---

src/modules/ticket-fields/TicketField.tsx

…onsistent with master branch
JIRA: https://zendesk.atlassian.net/browse/CD-3071
This was an issue noticed by Ashwin, our product manager, but only on the beta theme. Lookup fields were not working on the `beta` branch of `copenhagen_theme` but were fine on the `master` branch.
The issue was that the equality check changed from this line in the `master` branch: https://github.com/zendesk/copenhagen_theme/blob/c9a30bd6bc4ae5ea4d1023b1d9ba2c88c12d62a1/src/modules/new-request-form/NewRequestForm.tsx#L326
The update was checking if organizationField was !== to undefined, evaluating to true since it was actually `null` and thus `organizationField?.value` was `undefined` leading to a `400 Bad Request` from the `/autocomplete` endpoint.
Before:
After:

fix: update organizationField equality check so that it is consistent with master branch

---

src/modules/new-request-form/NewRequestForm.tsx

In some cases, where fields get moved around because of end user conditions, the rendering of the fields was not working as expected. This was due to the fact that the key was not being passed correctly to the components. This fix ensures that all components are provided with the correct key to prevent issues with rendering.
This is an example reported in a Z2 ticket, but the issue could be present for more fields since we were not passing the key correctly for most of them
https://github.com/user-attachments/assets/5dff4ac1-ce06-4fdd-9e28-3f5d2f66efe3
https://github.com/user-attachments/assets/3435c76b-c4dc-4f1e-b6bc-b5d4f4c24167

fix(new-request-form): fixed rendering issues with conditional fields

---

translations.yml

This PR adds a new string to rename the "scoped search" setting from "Scoped search in Knowledge Base" to ""Scoped search in Help Center"

chore: added new translation string for the scoped search setting

---

package.json
src/modules/new-request-form/fields/attachments/Attachments.tsx
yarn.lock

We were determining the mime type for attachments in the theme using the `mime` library, and passing this info to the Upload Attachments API in the `Content-Type` header.
This was implemented in #520 to support some specific files, as suggested by the team that owns the endpoint, but it still causes some issues with some files (namely `.log` files not encoded as UTF-8).
The team advises passing `application/octet-stream` as type if the browser doesn't detect the type automatically. This solves the upload issue for all the problematic files we know so far, and we can stop bundling a library just to determine the mime type of the uploaded files.

fix: fixed upload of some type of attachments

---

src/modules/service-catalog/components/service-catalog-item/CollapsibleDescription.tsx

We were setting `text-align: left` in the `CollapsibleDescription` component, which was causing the description text to be left-aligned even in RTL languages.
The rule is not needed, and we can rely on the default alignment which is right-aligned in RTL languages.
Before
After

fix(service-catalog): fix description alignment in RTL languages

---

src/modules/service-catalog/ServiceCatalogList.tsx

Some languages make use of the `few` and `many` plural forms, such as arabic. When we added the Services count, we only provided values for `one` and `other` which led to errors when displaying the counter in the page.
This PR adds a default value for all the other forms, in order to display the counter correctly. The translations for the counter will be added in another PR.

fix: add missing values for services count string

---

README.md
src/modules/service-catalog/translations/en-us.yml

We add new strings for the Services count in our beta branch. However, given that our translation tool only picks up new strings from master, we did not get the required translation variants.
This PR adds the strings to master in order to get the translations. It also updates the README to include all the necessary plural forms.

chore: add service catalog count strings for translation

---

src/modules/service-catalog/translations/en-us.yml

We have added new strings related to the Services search feature in our beta branch. However, given that our translation tool only picks up new strings from master, we did not get the required translation variants.
This PR adds the strings to master so we are able to get the translations, which will then be added to the beta branch in a future PR.

chore: add services search strings for translation

---

templates/service_list_page.hbs

This one translation string was missing and we had hardcoded page title. Now we can use translation passed from HC in handlebars. 
[Jira issue GG-4127](https://zendesk.atlassian.net/browse/GG-4127)

Use translation for page title

---

assets/service-catalog-bundle.js
src/modules/service-catalog/components/service-catalog-item/CollapsibleDescription.tsx

Render service item description with html in service item page.
Jira: [https://zendesk.atlassian.net/browse/GG-4240](https://zendesk.atlassian.net/browse/GG-4240)

feat: render service item description with html in service item page

---

src/modules/service-catalog/components/service-catalog-item/CollapsibleDescription.tsx
styles/_service_catalog.scss
styles/index.scss

This PR defines a `service-catalog-description` CSS class in the SASS files, which contains some styles needed to properly show content created by the WYSIWYG editor in Knowledge Admin. The class is then added to the `CollapsibleText` component.
The class uses the `content-body` mixin, also used for the article body and in the community pages. The build process will generate the needed classes in the main `styles.css` file.
Example of some fixed styles:
Before - list bullet points and blockquote are not styled correctly
After

fix: added styles for service catalog description

---

package.json
src/modules/service-catalog/components/service-catalog-list/ServiceCatalogListItem.spec.tsx
src/modules/service-catalog/components/service-catalog-list/ServiceCatalogListItem.tsx
yarn.lock

Use the colours from the team settings in the services list item cards. The main changes are:
- We will use the brand colour (`primaryHue`) as the border colour on hover and maintain the same.
- Use the text color (`foreground `) as the text colour for the cards.
- Updates `nwsapi` to fix a problem preventing the tests for on hover user events to work when implemented using [userEvent](https://github.com/testing-library/user-event). You can check [this issue](https://github.com/testing-library/jest-dom/issues/594).
https://github.com/user-attachments/assets/344bdbda-259f-4332-ac7d-f8bf87f01718
[GG-4255]: https://zendesk.atlassian.net/browse/GG-4255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GG-4255: fix: Use colours from team settings in the services page

---

src/modules/service-catalog/components/item-thumbnail/ItemThumbnail.tsx
src/modules/service-catalog/components/service-catalog-item/CollapsibleDescription.tsx
src/modules/service-catalog/components/service-catalog-item/ItemRequestForm.tsx
src/modules/service-catalog/components/service-catalog-list/ItemThumbnail.tsx
src/modules/service-catalog/components/service-catalog-list/ServiceCatalogListItem.spec.tsx
src/modules/service-catalog/components/service-catalog-list/ServiceCatalogListItem.tsx
src/modules/service-catalog/data-types/ServiceCatalogItem.ts
src/modules/service-catalog/hooks/useItemFormFields.spec.ts

Display thunbnails in the Service list page - https://zendesk.atlassian.net/browse/GG-4327
Display thunbnails in the Service page - https://zendesk.atlassian.net/browse/GG-4328
I joined both tickets as they are very similar, using same components and BL. 
Index:
Show:
Index:
Show:
Index:
Show with thumbnail:
Show with fallback icon:

feat: display thumbnails in the services item list

---

src/modules/new-request-form/translations/en-us.yml

For some reason, we are missing a couple of translation strings that are present on master on the beta branch. Probably, I did something wrong when I previously merged these changes from master.
Note for localization: these strings are already approved and present on the [master branch](https://github.com/zendesk/copenhagen_theme/blob/27b9a13281960ec5b7d9cd21cca7ee78bdfecec7/src/modules/new-request-form/translations/en-us.yml#L190). I am just bringing them here as well to avoid us deleting them when we merge this branch on master

chore: restore missing translation strings for the new-request-form module

---

src/modules/ticket-fields/fields/LookupField.test.tsx
src/modules/ticket-fields/fields/LookupField.tsx

Previously we were only supporting a single custom dynamic filter. This work appends dynamic query params for each defined filter.
Before:
After:

feat: adds support for multiple dynamic filters

---

src/modules/ticket-fields/translations/en-us.yml

This PR adds a translation string that was missing, and it will be used in #655 when translations are ready

chore: added missing tranlsation string for multi-level dropdown back option

---

templates/search_results.hbs

Reorder the title elements for search results filters to ensure that the reading order of content is logical for screen reader users. 
https://zendesk.atlassian.net/browse/KIAW-1464
The page looks the same as before:

style: change order of the filters title with toggle button

---

templates/search_results.hbs

Accessibility change: change aria-label for subfilter menu to be aligned with the visible text label for posts and articles subfilters. 
https://zendesk.atlassian.net/browse/KIAW-1463

[KIAW-1463] Change aria-label for subfilters menu button 

---

src/modules/approval-requests/renderApprovalRequest.tsx
src/modules/approval-requests/renderApprovalRequestList.tsx

This PR updates renderApprovalRequest and renderApprovalRequestList functions to ensure that translations from the shared locales are also loaded. 
- https://zendesk.atlassian.net/browse/PDSC-109

fix: include shared baseLocale translations in ApprovalRequest loader
