manifest.json, style.css, styles/_mixins.scss
Ports changes from https://github.com/zendesk/help_center/pull/14755
JIRA: [HCD-1463](https://zendesk.atlassian.net/browse/HCD-1463)
none
=> Port changes from Help Center

templates/article_page.hbs
Updating the article template for the new edited_at property
@ilkkao @aliciacatalina
=> Updatign the article template to use the new edited_at property

templates/contributions_page.hbs, templates/user_profile_page.hbs
JIRA: [HCD-1602](https://zendesk.atlassian.net/browse/HCD-1602)
=> Remove syntax-breaking closing tags

translations.yml
This PR adds the OOTB settings related strings to the translation file.
@zendesk/delta @zendesk/i18n 
JIRA: [HCD-1832](https://zendesk.atlassian.net/browse/HCD-1832)
Low.
=> Add OOTB strings for translation

translations.yml
NOTE: String Sweep will be suspended for this repo until this PR is merged or closed!
/cc @zendesk/delta
Low. English edits and title improvements.
=> [LOCAL-44] Strings: reverse sweep (auto)

translations.yml
=> Fix a typo in translations

translations.yml
This PR marks the affected keys and creates new key with the fix.
@zendesk/delta @zendesk/i18n
=> Fix typos in translation keys

templates/header.hbs
Ported PR: https://github.com/zendesk/help_center/pull/15629
None
=> Port changes of logo alt text to mention help center home page

templates/article_page.hbs, templates/community_post_page.hbs, templates/request_page.hbs, templates/subscriptions_page.hbs, templates/user_profile_page.hbs
Ported PR: https://github.com/zendesk/help_center/pull/15609
None
=> Port removal of avatar alt texts

script.js, styles/_header.scss, templates/header.hbs
Ported PR: https://github.com/zendesk/help_center/pull/15602
None
=> Ports improval of accessibility on the collapsible navigation menu

styles/_user-profiles.scss
Ported PR: https://github.com/zendesk/help_center/pull/15591
None
=> Port adding an outline color to edit button

templates/document_head.hbs
Ported PR: https://github.com/zendesk/help_center/pull/15578
None
=> Port the removal of scale attributes on document head

styles/_search.scss, styles/_status-label.scss
Ported PR: https://github.com/zendesk/help_center/pull/15571
None
=> Port the background change of open ticket

templates/request_page.hbs
Ported PR: https://github.com/zendesk/help_center/pull/15956
None
=> Port quoting out name title attribute on the request page

styles/_user.scss
Needed for keyboard navigation.
=> Adds focus style for user menu

style.css
This PR compiles the SCSS stylesheets after changes introduced in #18.
@zendesk/delta
=> Compiles the SCSS stylesheets

manifest.json
Bumps version in the manifest
cc @zendesk/delta
=> Bump version to 1.4.4

manifest.json, templates/new_request_page.hbs, templates/request_page.hbs
cc: @zendesk/guide-growth 
Low
=> Remove the use of deprecated chat helpers

style.css, styles/_icons.scss
=> removed glpus icon from icons.scss

manifest.json, script.js, style.css, styles/_collapsible-nav.scss, styles/_collapsible-sidebar.scss, styles/_my-activities.scss, styles/_user-profiles.scss, templates/article_page.hbs, templates/contributions_page.hbs, templates/request_page.hbs, templates/requests_page.hbs, templates/subscriptions_page.hbs, templates/user_profile_page.hbs
This PR adds keyboard navigation to `collapsible-nav` and `collapsible-sidebar`.
=> Make collapsible menus keyboard accessible

manifest.json, style.css, styles/_category.scss, styles/_comments.scss, styles/_community.scss, styles/_home-page.scss, styles/_post.scss, styles/_request.scss, styles/_search_results.scss, styles/_status-label.scss, templates/article_page.hbs, templates/category_page.hbs, templates/community_post_list_page.hbs, templates/community_post_page.hbs, templates/community_topic_list_page.hbs, templates/community_topic_page.hbs, templates/home_page.hbs, templates/request_page.hbs, templates/search_results.hbs, templates/section_page.hbs
This PR refactors some pages to ensure:
- each page has an H1 level heading;
- each page does not skip heading levels;
This is part of an effort to improve accessibility in the theme.
=> Improve page headings

manifest.json, style.css, styles/_blocks.scss, styles/_mixins.scss
JIRA: https://zendesk.atlassian.net/browse/GG-114
=> [GG-114] Fix focus styling for Block style links

style.css, styles/_base.scss, styles/_search_results.scss, templates/search_results.hbs
JIRA: https://zendesk.atlassian.net/browse/GG-118
=> [GG-118] Make search results icons accessible

manifest.json
I forgot to bump the version for https://github.com/zendesk/copenhagen_theme/pull/109
=> Update manifest version

style.css, styles/_base.scss, styles/_recent-activity.scss
cc @zendesk/guide-growth 
JIRA: https://zendesk.atlassian.net/browse/GG-888
=> [GG-888] Align theme with Recent Activity API v2

.github/workflows/lighthouserc.json, .github/workflows/main.yml, .github/workflows/theme_upload.rb
Adds a lighthouse CI check to set a baseline for a11y issues
=> Initial lighthouse setup with actions

.github/workflows/main.yml, .github/workflows/theme_upload.rb
This PR updates the used method for authentication in tests.
=> Update tests auth to use token

manifest.json, templates/home_page.hbs
Depends on these strings to be translated: https://github.com/zendesk/help_center/pull/19804
JIRA: https://zendesk.atlassian.net/browse/GG-205
=> [GG-205] Fix heading hierarchy for home page

manifest.json, script.js
=> script.js: Auto focus fields that have error notifications under them

manifest.json, style.css, styles/_article.scss, templates/article_page.hbs
- Aligns the styling of headings on the article page (requested by @DovileM )
- Addresses the confusing layout for assistive technologies.
=> [COMM-96] Change article page layout

.github/workflows/lighthouserc.json
Update `collect` settings and env for tests.
=> Run tests on desktop

.github/workflows/lighthouserc.json
We have found some instability in the final score result for the same page. Needs to be investigated further.
=> Adjust lighthouse scores

.github/workflows/main.yml
Setting versions explicitly to avoid gem versioning conflicts.
Low
=> Set gem versions explicitly

.github/workflows/lighthouserc.json
Reverts zendesk/copenhagen_theme#139
=> Revert "Exclude tabindex checks from accessibility score"

manifest.json, style.css, styles/_variables.scss
The search input text color didn't have sufficient contrast, so this increases it. New text color supplied by @DovileM 
https://zendesk.atlassian.net/browse/GG-945
=> [GG-945] Increase color contrast of input text

manifest.json, style.css, styles/_notifications.scss, styles/index.scss
Adds notification styles into theme.
JIRA: https://zendesk.atlassian.net/browse/GG-915
=> [GG-915] Add notifications styles

manifest.json, style.css, styles/_tables.scss
This fixes the table rendering for v2.
cc @TetianaG
=> [GG-990] Fix table borders in v2

manifest.json, style.css, styles/_pagination.scss
=> Add cursor-esque paginiation style for v2

.github/workflows/theme_upload.rb
Updating tests to use a new API.
=> Update theme upload

manifest.json, style.css, styles/_share.scss
JIRA: https://zendesk.atlassian.net/browse/GG-1005
=> [GG-1005] Fix misaligned focus ring for share icons

style.css, styles/_article.scss, styles/_buttons.scss, styles/_vote.scss, templates/article_page.hbs
Reverts zendesk/copenhagen_theme#169
=> Revert "Aligning vote buttons with api v2"

manifest.json, style.css, styles/_buttons.scss, styles/_dropdowns.scss
=> Add `cursor: pointer;` where it's missing

manifest.json, style.css, styles/_buttons.scss
Addresses visual bugs in Firefox and Safari
=> Add transparent background-color to `.button`

manifest.json, templates/search_results.hbs
Applies the same logic to the subfilters, as wee have for filters
=> Fix ARIA for subfilters on search page

manifest.json
=> Bump the theme version

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yml, .releaserc, README.md, bin/update-manifest-version.sh, package.json, yarn.lock
This PR sets up automatic releases for the copenhagen theme:
- it relies on the usage of [conventional commits standard](https://www.conventionalcommits.org/en/v1.0.0/) to help automate semantic versioning;
- it relies on [`husky`](https://github.com/typicode/husky) and [`commitlint`](https://github.com/conventional-changelog/commitlint) to validate commit messages based on that standard;
- it relies on [Github actions](https://github.com/features/actions) and [`semantic-release`](https://github.com/semantic-release/semantic-release) to automate releases;
- it updates the `README.md` to document these changes;
- it adds a pull request template with a checklist to help developers follow these guidelines.
Workflow on commit:
- `commitlint` will verify that each commit message follows the …
=> chore(release): automate copenhagen theme releases

.github/workflows/release.yml, CHANGELOG.md
This PR updates the automatic releases to use the [Copenhagen Theme Bot](https://github.com/zd-svc-github-copenhagen-theme) account.
It also removes a duplicated entry in the changelog due to a manual release.
=> Use Copenhagen Theme Bot for releases

.github/workflows/lighthouserc.json, .github/workflows/main.yml, .github/workflows/puppeteer-script.js
- adding puppeteer script for login
=> Add tests for pages behind login

style.css, styles/_user-profiles.scss, templates/user_profile_page.hbs
Fixes alignment issue in the "Badges (n)" tab.
=> Updated styling to fix alignment issue

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a mobile check to the PR template, so developers don't forget to test changes in mobile.
=> chore: add mobile check to the PR template

templates/article_page.hbs
This PR updates the article template to use the translated string for "Download" `{{t 'download'}}`.
=> fix(article): use t helper for article attachments download string

templates/new_request_page.hbs, templates/request_page.hbs
[COMM-1271]
---
Relates to https://github.com/zendesk/help_center/pull/21272
[COMM-1271]: https://zendesk.atlassian.net/browse/COMM-1271
=> [COMM-1271] Enable WYSIWYG editor on (new) request page

templates/request_page.hbs
This PR updates the request page template to use the newly added [`request` properties](https://developer.zendesk.com/apps/docs/help-center-templates/objects#request-object) `type_tile` and `priority_title`. These properties expose the title to be shown to end users for these fields (defined in Support):
=> fix(request): render title values for priority and type fields

script.js, style.css, styles/_section.scss, templates/section_page.hbs
Removing "See all" subsections and adding subsections pagination to Section template.
=> feat: add subsections pagination to section template

script.js
=> fix(script): [COMM-1283] Fix null error

templates/category_page.hbs, templates/section_page.hbs
Use scoped search based on category user is in for sections and category page.
https://support.zendesk.com/agent/tickets/6154937
=> fix(search): Use scoped search based on category user is in 

templates/user_profile_page.hbs
test(user): This PR  adds DOM ids to aid automated cypress tests found in https://github.com/zendesk/help_center/pull/23301.
The ids are added in the user profile page  for the value of the  labels  Following, Followed by, Votes and Subscription.
=> test(user): adding ids for cypress test

templates/user_profile_page.hbs
[COMM-1046]: https://zendesk.atlassian.net/browse/COMM-1046
=> fix: [COMM-1046] Fix an issue with a self-closing div tag

templates/header.hbs
This change adds a menu item to the user dropdown menu, which will open the new contact details modal, introduced in Help Center.
=> feat: menu item for upcoming contact details modal

style.css, styles/_search.scss
Customer report https://support.zendesk.com/agent/tickets/9803987
| Before | After |
| --- | --- |
| ![IMG_3170](https://user-images.githubusercontent.com/5488576/143203739-645c04e9-073d-42b7-add2-71aa363f5700.PNG) | ![IMG_3172](https://user-images.githubusercontent.com/5488576/143203729-7603660c-99d3-448a-8592-ad5512cc41c4.PNG) |
=> [GG-2415] Fix search input field background color in iOS

templates/article_page.hbs, templates/community_post_page.hbs, templates/request_page.hbs, templates/user_profile_page.hbs
Improving a11y for the agent-markers SVGs.
=> fix: add aria-label on agent markers

manifest.json, templates/requests_page.hbs
Add request list beta setting to manifest file.
~Blocked by: https://github.com/zendesk/copenhagen_theme/pull/309~
https://zendesk.atlassian.net/browse/GG-2335
=> Add the request list beta setting

.github/workflows/puppeteer-script.js
This PR aims to fix the lighthouse check.
In the end, I could not figure out why exactly this check is failing. 
I managed to run the `puppeteer-script.js` locally and everything was working fine, but it was not working properly when running via GH Actions, which made my life very difficult.
Lastly, following Niklas's suggestion, I introduce a `sleep` in puppeteer-script.js and to my surprise, this `sleep` fixed the lighthouse check. 
Niklas and I looked for a better and more elegant solution than the `sleep`, we tried a bunch of different puppeteer methods like: `page.waitForFunction, page.evaluate, waitUntil` but without luck 😞. So in the end I gave up and decided to open this PR with the old fashion `sleep`.
=> [GG-2810] Fixes lighthouse

style.css, styles/_recent-activity.scss, styles/_search_results.scss, templates/article_page.hbs, templates/community_post_list_page.hbs, templates/community_post_page.hbs, templates/community_topic_page.hbs, templates/request_page.hbs, templates/search_results.hbs, templates/user_profile_page.hbs
This PR introduces some improvements that will enhance the usage of screen readers. Prior to this change the meta-data elements were interpreted as list items.
=> Screen reader improvements

manifest.json
This PR updates Copenhagen Theme to use Templating API v3 ([docs](https://developer.zendesk.com/documentation/help_center/help-center-templates/v2/)).
=> feat: update theme to use Templating API v3

package.json, yarn.lock
Brings in latest version of `zcli`.
=> Bump zcli to latest version

templates/new_request_page.hbs
Using the new naming introduced in https://github.com/zendesk/help_center/pull/27808
=> fix: request_form has been renamed to new_request_form

src/navigation.js
Reverts zendesk/copenhagen_theme#376
Fixing https://support.zendesk.com/agent/tickets/11759050
=> Revert "Remove aria-expanded attribute from section tag in search result page"

assets/new-request-form.js, assets/vendor.js, src/modules/new-request-form/NewRequestForm.tsx, src/modules/new-request-form/data-types/RequestForm.tsx, src/modules/new-request-form/data-types/TicketForm.ts, src/modules/new-request-form/data-types/index.ts, src/modules/new-request-form/ticket-form-field/TicketFormField.tsx, templates/new_request_page.hbs
This PR replaces the manual serialization of the form data with the new temporary `{{new_request_form.to_json}}`.
It also introduces the type for the `new_request_form` object and aligns the `display_name` property of the `ticket_forms` object with the one returned by the Help Center template, to make it easier to eventually switch to the Curlybars JSON serialization in the future
=> refactor: use json serialized data

README.md
This is just a dummy PR to trigger a release after the [revert](https://github.com/zendesk/copenhagen_theme/pull/398).
=> fix: a dummy PR to trigger a release after revert

package.json, yarn.lock
Brings in the latest version of `zcli` which adds support for logging in to different environments.
=> chore: upgrading zcli to latest version

assets/new-request-form.js, assets/vendor.js, src/modules/new-request-form/NewRequestForm.tsx, src/modules/new-request-form/fields/DropDown.tsx, templates/new_request_page.hbs
=> feat: organization field

assets/new-request-form.js, assets/shared.js, assets/vendor.js, src/modules/new-request-form/NewRequestForm.tsx, src/modules/new-request-form/fields/Checkbox.tsx
Rendering and handling submission/validation of ticket fields of type `checkbox`.
=> feat: support for checkbox fields

templates/request_page.hbs
[Team Ultra has been working on exposing a new property in the request show presenter](https://github.com/zendesk/help_center/pull/28939) — `satisfaction_response` — in order to implement the new CSAT details.
This PR aims at augmenting the Copenhagen Theme in order to consume said property, and render the CSAT details as per [the designs in Figma](https://www.figma.com/file/SJX5vix08L1ZOF2Y93vsRL/Customisable-CSAT?type=design&node-id=5607%3A4647&mode=design&t=0i2IWt9B0x8Dfg9X-1).
=> Add survey response to request details

templates/new_request_page.hbs
We can only merge this PR once the new `json` helper becomes available.
=> Use new json helper

templates/header.hbs
=> Remove stray </li>

src/modules/new-request-form/translations/en-us.yml
This PR adds a string to be used in the New Request Form
=> chore: added translation string for the New Request Form

README.md, rollup.config.mjs
This PR adds documentation about the JavaScript modules containing the React components
=> docs: added information about the React components

CHANGELOG.md, manifest.json
This reverts commit 3014a4dd41adcfb7d07556520151a560253f04cd.
Third attempt after #510 and #511. Reverting v4.1.1 and deleting tags
=> Revert "chore(release): 4.1.1"

assets/service-catalog-bundle.js, assets/shared-bundle.js, src/modules/service-catalog/ServiceCatalogItemPage.tsx, src/modules/service-catalog/ServiceCatalogList.tsx, src/modules/service-catalog/components/service-catalog-list-item/EmptyState.tsx, src/modules/service-catalog/components/useItemFormFields.tsx, src/modules/service-catalog/renderServiceCatalogItem.tsx, src/modules/service-catalog/renderServiceCatalogList.tsx, src/modules/service-catalog/translations/en-us.yml, src/modules/service-catalog/useNotifyError.tsx, src/modules/service-catalog/useServiceCatalogItem.tsx, src/modules/shared/error-boundary/ErrorBoundary.tsx, src/modules/shared/error-boundary/ErrorScreen.tsx, src/modules/shared/error-boundary/index.ts, src/modules/shared/index.ts, src/modules/shared/translations/en-us.yml, templates/service_list_page.hbs, templates/service_page.hbs
Added better handling of errors with ErrorBoundary. Now when something will go wrong in service catalog components the view won't crush and show a blank page but show proper error screen (waiting for design). Added ErrorBoundary component to shared folder so it can be used in other modules also. 
Jira issue: [Implement ErrorBoundary for error handling](https://zendesk.atlassian.net/browse/GG-4007)
=> feat: add error boundary for service catalog

templates/search_results.hbs
Adding `generative_answers` helper to the main theme.
=> feat: added generative_answers helper to search results page

package.json, yarn.lock
This PR updates `dompurify` to the latest available version, to address a security vulnerability
=> fix(new-request-form): update dompurify

src/modules/approval-requests/translations/en-us.yml
This PR adds translations to be used in the Approval request ticket details page. 
[JIRA](https://zendesk.atlassian.net/browse/SW-3056)
=> fix: add approval request priorty level translations

src/Dropdown.spec.js, src/modules/approval-requests/ApprovalRequestListPage.test.tsx, src/modules/approval-requests/components/approval-request-list/ApprovalRequestListFilters.test.tsx, src/modules/approval-requests/components/approval-request-list/ApprovalRequestListTable.test.tsx, src/modules/approval-requests/components/approval-request/ApproverActions.test.tsx
Update `userEvent` import to remove warning.
=> chore: update userEvent imports to remove warnings

src/modules/service-catalog/components/service-catalog-item/CollapsibleDescription.tsx
This PR improves the logic for collapsing long descriptions in the CollapsibleDescription component.
Previously, the ToggleButton visibility was based solely on the `description.length > DESCRIPTION_LENGTH_THRESHOLD` condition. However, this led to incorrect behavior in real scenarios:
* Even short visible descriptions (e.g. a couple of `<p>` tags) could contain long HTML content like images or attachments, inflating the `description.length` and incorrectly triggering the toggle button.
* The toggle would appear even when there was nothing to collapse.
- https://zendesk.atlassian.net/browse/GG-4486
Replaced the static `DESCRIPTION_LENGTH_THRESHOLD` check with a dynamic calculation of actual visual overflow. The new logic uses the CSS `line-clamp` property to compare:
`scrollHeight` - the …
=> fix: avoid unnecessary toggle
